#!/usr/bin/env bash
################################################################################
#
# Bake is a shell script for running CakePHP bake script
#
# CakePHP(tm) :  Rapid Development Framework (https://cakephp.org)
# Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
#
# Licensed under The MIT License
# For full copyright and license information, please see the LICENSE.txt
# Redistributions of files must retain the above copyright notice.
#
# @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
# @link          https://cakephp.org CakePHP(tm) Project
# @package       app.Console
# @since         CakePHP(tm) v 1.2.0.5012
# @license       https://opensource.org/licenses/mit-license.php MIT License
#
################################################################################

CONSOLE=$(dirname -- "$(readlink -e "$0")")
APP=$(dirname "$CONSOLE")

if [ -x "$(command -v cygpath)" ]; then
	APP=$(cygpath -m "$APP")
fi

exec php "$CONSOLE/cake.php" -working "$APP" "$@"
